Задание Sprint1 выполнено
perminovaa/Frontend-4-X-Rubius-Academy pull request #1
Opened 2023-03-26 09:48 UTC by perminovaa

2023-03-30 16:14 UTC, euge-huge requested changes
Работа отличная!

Код приятно смотреть, читать и оставлять комментарии, спасибо!

Так держать!

2023-03-30 16:14 UTC, euge-huge commented on main.css
> +    min-width: 1440px;  /*зафикс.размер страницы*/
`можно лучше`

Применить ширину для всего body - не лучшая идея)
По этой причине не удается разместить картинку бэкграунда на весь экран без отступов.

Лучше сделать отдельный класс .container, который будет иметь эти свойства ширины и добавлять его там, где нужно ограничить контейнер по ширине.

Например:
```
<body>
  <header>
    <div class="container">этот контент будет ограничен по ширине</div>
    <div>а этот нет =)</div>
  </header>

  <section>
    <div class="container">этот контент будет ограничен по ширине</div>
  </section>
</body>

```

2023-03-30 16:14 UTC, euge-huge commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
Сюда лучше добавить строку еще, чтобы браузер корректно воспринимал размеры)

`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

2023-03-30 16:14 UTC, euge-huge commented on index.html
`отлично`

У кода хороший стиль, отступы между блоками внутри, хорошо!

2023-03-30 16:14 UTC, euge-huge commented on index.html
Очень удобно читается и выглядит красиво)

2023-03-30 16:14 UTC, euge-huge commented on main.css
> +}
`отлчино`

Выглядит красиво и уместно, лайк!

2023-03-30 16:14 UTC, euge-huge commented on main.css
> +    position: sticky;
Прикольно, что он прилипший, но когда листаешь страницу, то видно, что он на всю ширину, а вот .container призван исправить эту ситуацию, а контент внутри ограничить)

2023-03-30 16:14 UTC, euge-huge commented on index.html
> +                    <li><a href="#contact">Контакты</a></li>
`можно лучше`

Можно попробовать, чтобы при увеличении ссылок, они переползали на новую строчку, которые не влезают

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/58856916/228896233-a25703b5-7aa6-4f17-9ea5-a7143279786a.png">

Могут пригодиться свойства:
```
min-width: fit-content;
flex-wrap: wrap;
flex-grow: ...;
gap: ...px ...px;
```

2023-03-30 16:14 UTC, euge-huge commented on index.html
> +                            <button>Записаться онлайн</button>
`нужно поправить`

Сделать лапку при наведении на кнопку, чтобы было понятно, что она кликабельна)

2023-03-30 16:14 UTC, euge-huge commented on index.html
> +                            <img src="/image/video.png" alt="video">
`можно лучше`

Можно сделать, чтобы у картинки всегда были закруглены края, даже если поменяем
Сделать, чтобы лапка кликабельная была (cursor: pointer)

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/58856916/228897450-03c645fd-1c0e-4702-b50e-a9d6ea3bb1a7.png">

А вот за то, что я поменял и ничего не сползло, размеры сохранились - лайк не глядя :)

2023-03-30 16:14 UTC, euge-huge commented on index.html
> +                        </div>
`можно лучше`

Поработать над переполняемостью

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/58856916/228898044-bd325475-37a9-4c12-ab19-f53094d4d80b.png">

Нужно, чтобы новый ряд появлялся, а вряду всегда было по 3 элемента)

`flex-wrap: wrap;` может помочь)

2023-03-30 16:14 UTC, euge-huge commented on main.css
> +}
Это лучше вынести в самое начало ко всем общим блокам (там где body h1 и тд)

2023-03-30 16:14 UTC, euge-huge commented on main.css
> +.Headerbackgroung {
С большой буквы стили называть не принято)

2023-03-30 16:14 UTC, euge-huge commented on main.css
> +}
Стили которые касаются глобальных элементов html в начало)

2023-03-30 16:14 UTC, euge-huge commented on main.css
`если интересно`

Можно посмотреть стайл гайд здесь:
https://learn.javascript.ru/css-format

Более полезно обратить на порядок стилей в этом гайде (вырезка ниже):

Рекомендуется располагать свойства в следующем порядке:
Сначала положение элемента относительно других: position, left/right/top/bottom, float, clear, z-index.
Затем размеры и отступы: width, height, margin, padding…
Рамка border, она частично относится к размерам.
Общее оформление содержимого: list-style-type, overflow…
Цветовое и стилевое оформление: background, color, font…

2023-03-31 03:53 UTC, perminovaa commented on index.html
> +                        </div>
Спасибо за оценку!) Я могу исправленные замечания сдать в ветке Спринт2? т.к. все замечания я уже исправила в процессе выполнения задания спринта2.

2023-04-08 10:07 UTC, euge-huge approved these changes

2023-04-10 09:07 UTC, merged